language: ruby
rvm:
- 2.1.3
env:
- RAILS_ENV=test
before_script:
- psql -c "CREATE ROLE think200_test WITH PASSWORD 'think200' CREATEDB LOGIN" -U postgres
- cp config/database.yml-default config/database.yml
- bundle exec rake db:setup
- cp config/secrets.yml-default config/secrets.yml
