#!/bin/bash

#
# 3 workers: premium queue
#
echo "Starting premium queue worker..."
env BACKGROUND=yes QUEUES=premium          TERM_CHILD=1 RESQUE_TERM_TIMEOUT=7 ~/.rvm/bin/rvm default do bundle exec rake resque:work

#
# 1 worker: premium and standard queues
#
echo "Starting standard queue worker..."
env BACKGROUND=yes QUEUES=premium,standard TERM_CHILD=1 RESQUE_TERM_TIMEOUT=7 ~/.rvm/bin/rvm default do bundle exec rake resque:work
